In [49]:
import numpy as np
import pandas as pd

In [51]:
# Creating a DataFrame
data = {'Name':['John','Anna','Peter','Linda'], 
        'Age':[28,34,29,42],
        'City':['New York','Paris','Berlin','London'],
        'Salary':[65000,70000,62000,85000]
       }
df = pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [53]:
data_list = [['John',28,'New York',65000],
             ['Anna',34,'Paris',70000],
             ['Peter',29,'Berlin',62000],
             ['Linda',42,'London',85000]
            ]
df2 = pd.DataFrame(data_list)
df2

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [55]:
columns = ['Name','Age','City','Salary']
df2 = pd.DataFrame(data_list,columns=columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [57]:
# Selection and Indexing of Columns
df2['Name']

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: object

In [59]:
df2['City']

0    New York
1       Paris
2      Berlin
3      London
Name: City, dtype: object

In [61]:
df2[['Name','City']]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

In [107]:
# Creating a new column
df2['Designation'] = ['Doctor','Engineer','Doctor','Engineer']
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000    Engineer
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000    Engineer

In [109]:
# Removing Columns
# df2.drop('Designation',axis = 1,inplace = True)
df2.drop(["City","Salary"],axis = 1)

    Name  Age Designation
0   John   28      Doctor
1   Anna   34    Engineer
2  Peter   29      Doctor
3  Linda   42    Engineer

In [115]:
df2.drop(0,axis = 0)

    Name  Age    City  Salary Designation
1   Anna   34   Paris   70000    Engineer
2  Peter   29  Berlin   62000      Doctor
3  Linda   42  London   85000    Engineer

In [117]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000    Engineer
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000    Engineer

In [121]:
# Selecting Rows
df2.loc[0]

Name               John
Age                  28
City           New York
Salary            65000
Designation      Doctor
Name: 0, dtype: object

In [123]:
df2.loc[[0,1]]

   Name  Age      City  Salary Designation
0  John   28  New York   65000      Doctor
1  Anna   34     Paris   70000    Engineer

In [127]:
df.iloc[3]

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

In [129]:
# Selecting Subsets of Rows and Columns
df.loc[[0,1]][['City','Salary']]

       City  Salary
0  New York   65000
1     Paris   70000

In [131]:
# Conditional Selection
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000    Engineer
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000    Engineer

In [135]:
# Find those people whose age is above 30
df2[df2['Age']>30]

    Name  Age    City  Salary Designation
1   Anna   34   Paris   70000    Engineer
3  Linda   42  London   85000    Engineer

In [143]:
# Find those people whose age is above 30 and city is paris
df2[(df2['Age']>30) & (df2['City'] == 'Paris')]

   Name  Age   City  Salary Designation
1  Anna   34  Paris   70000    Engineer